name: Node CI

on: [push, pull_request]

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run client unit tests
        run: yarn run test:client:unit
      - name: Run client e2e tests
        run: yarn run test:client:e2e
      - name: Run server unit tests
        run: yarn run test:server:unit
      - name: Run server e2e tests
        run: yarn run test:server:e2e
      - name: Build
        run: yarn run build